#pragma once

#include <ntddk.h>
#include <wdf.h>
#include <hidport.h>
#include <vhf.h>

#define OCM_REPORT_ID 0x06
#define OCM_REPORT_SIZE 64
#define OCM_OUTPUT_QUEUE_CAPACITY 32

#define IOCTL_OCM_SUBMIT_INPUT_REPORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_OCM_GET_OUTPUT_REPORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA)

DEFINE_GUID(
    GUID_DEVINTERFACE_OPEN_CODEX_MICRO_VHF,
    0x73d3dc5e, 0xc3b1, 0x4d2f, 0x99, 0x20, 0x26, 0x54, 0x94, 0x8d, 0xb8, 0x7f);

typedef struct _DEVICE_CONTEXT {
    VHFHANDLE VhfHandle;
    WDFSPINLOCK ReportLock;
    ULONG OutputHead;
    ULONG OutputTail;
    ULONG OutputCount;
    ULONG OutputLengths[OCM_OUTPUT_QUEUE_CAPACITY];
    UCHAR OutputReports[OCM_OUTPUT_QUEUE_CAPACITY][OCM_REPORT_SIZE];
} DEVICE_CONTEXT, *PDEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, OcmGetDeviceContext)

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD OcmEvtDeviceAdd;
EVT_WDF_OBJECT_CONTEXT_CLEANUP OcmEvtDeviceContextCleanup;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL OcmEvtIoDeviceControl;
EVT_VHF_ASYNC_OPERATION OcmEvtVhfWriteReport;
